/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package voxpetrae.musicmetadata;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuItem;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

public class MainView extends Application {
    
    @Override
    public void start(Stage primaryStage) {
        final String MENU_BAR_ID = "#menuBar";
        final VBox vbox = new VBox();
        Scene scene = new Scene(vbox, 809, 809, Color.YELLOW);
        MenuBar menuBar = buildMenu();
        menuBar.setId(MENU_BAR_ID);
        //vbox.setPadding(new Insets(0, 10, 10, 0));
        ((VBox) scene.getRoot()).getChildren().addAll(menuBar);
        primaryStage.setTitle("Music Metadata - A minimalistic metadata handler");
        primaryStage.setScene(scene);
        //scene.setFill(Color.BLUEVIOLET); // just playing around
        //primaryStage.initStyle(StageStyle.DECORATED);
        primaryStage.show();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        launch(args);
    }

    /**
     * Creates the menu
     *
     * @return a MenuBar with eventhandlers set for the menu choices
     */
    private MenuBar buildMenu() {
        MenuBar menuBar = new MenuBar();
        Menu fileMenu = new Menu("File");
        Menu toolsMenu = new Menu("Tools");
        menuBar.getMenus().addAll(fileMenu, toolsMenu);
        MenuItem openFolder = new MenuItem("Open folder");
        MenuItem quit = new MenuItem("Quit");
        openFolder.setOnAction(openFolderView);
        quit.setOnAction(exitHandler);
        fileMenu.getItems().addAll(openFolder, quit);
        return menuBar;
    }

    /**
     * Sets exit action
     */
    EventHandler<ActionEvent> exitHandler = new EventHandler<ActionEvent>() {
        @Override
        public void handle(ActionEvent event) {
            System.out.println("Closing Music Metadata...");
            System.exit(0);
        }
    };
    /**
     * Opens a folder and does some checking
     */
    EventHandler<ActionEvent> openFolderView = new EventHandler<ActionEvent>() {
        @Override
        public void handle(ActionEvent event) {
            System.out.println("Open folder...");
        }
    };
    @Override
    public void stop(){
        System.out.println("Window closing...");
    }
}
